zip_exclude:
- ResourceUsageSummary
- analysis_source_association_metrics_table
- analyzeAmpInterfaceOffsetMetadata_resource_usage
- analyzeAmpOffsetMetadata_resource_usage
- analyzeCalibrateImageMetadata_resource_usage
- analyzeCalibrateMetadata_resource_usage
- analyzeDiaSourceTableTract_resource_usage
- analyzeInitialSummaryStats_resource_usage
- analyzeMatchedPreVisitCore_resource_usage
- analyzeMatchedVisitCore_resource_usage
- analyzeObjectTableCore_resource_usage
- analyzeObjectTableExtended_resource_usage
- analyzeObjectTableSurveyCore_resource_usage
- analyzePreSourceTableCore_resource_usage
- analyzeRecalibratedStarAssociation_resource_usage
- analyzeRecalibratedStarObjectMatch_resource_usage
- analyzeSingleVisitStarAssociation_resource_usage
- analyzeSingleVisitStarAstrometricRefMatch_resource_usage
- analyzeSingleVisitStarPhotometricRefMatch_resource_usage
- analyzeSingleVisitStar_resource_usage
- analyzeSourceAssociation_resource_usage
- assembleCoadd_resource_usage
- assembleDeepCoadd_resource_usage
- assembleTemplateCoadd_resource_usage
- associateAnalysisSource_resource_usage
- associateDiaSource_resource_usage
- associateIsolatedStar_resource_usage
- astrometricRefCatPreSourceVisit_resource_usage
- background_to_photometric_ratio
- bf_stats
- bias
- biasBin64
- biasBin8
- biasBootstrap
- biasMosaic64
- biasMosaic8
- bias_shifts
- bias_shifts_stats
- bias_stability_stats
- bright_defects_results
- calculateDiaObject_resource_usage
- calculated_quantiles
- calexp
- calexpBackground_skyCorr_visit_mosaic
- calexpBinned
- calexpSummary_metricsTable
- calexpSummary_metrics_perVisitTable
- calexpSummary_resource_usage
- calexp_skyCorr_visit_mosaic
- calibrateImage_resource_usage
- calibrate_metadata_metricsTable
- calibrate_metadata_visitTable
- calibrate_resource_usage
- catalogMatchPreVisit_resource_usage
- catalogMatchTract_resource_usage
- cbp_spot_forced
- cbp_spot_unforced
- ccdVisitTable
- cdfs_hlf_v2p1
- characterizeImage_resource_usage
- coadd_depth_summary_metrics_table
- coadd_depth_table
- compare_warp_artifact_mask
- computeObjectEpochs_resource_usage
- computeReliability_resource_usage
- consolidateAssocDiaSourceTable_resource_usage
- consolidateDiaObject_resource_usage
- consolidateDiaSourceTable_resource_usage
- consolidateDiaSource_resource_usage
- consolidateFullDiaObjectTable_resource_usage
- consolidateHealSparsePropertyMaps_resource_usage
- consolidateObjectTable_resource_usage
- consolidateObject_resource_usage
- consolidatePreSourceTable_resource_usage
- consolidateRecalibratedStar_resource_usage
- consolidateRefitPsfModelDetector_resource_usage
- consolidateSingleVisitStar_resource_usage
- consolidateSourceTable_resource_usage
- consolidateSource_resource_usage
- consolidateSsTables_resource_usage
- consolidateVisitDiaSource_resource_usage
- consolidateVisitSummary_resource_usage
- cosmos2020_classic_v2p2
- cosmos2025_v1
- cosmos_acs_iphot_200709
- cpBfkIsrExp
- cpBiasBootstrapIsrExp
- cpBiasIsrExp
- cpCrosstalkIsrExp
- cpDarkBootstrapIsrExp
- cpDarkForDefectsIsrExp
- cpDarkIsrExp
- cpDarkRemoveCRIsrExp
- cpDefectsIndividualIsrExp
- cpFlatBootstrapIsrExp
- cpFlatIsrExp
- cpIsrExp
- cpLinearizerIsrExp
- cpLinearizerNormalization1
- cpLinearizerNormalization2
- cpLinearizerPtcNormalization
- cpPtcFixupGainRatiosIsrExp
- cpPtcIsrExp
- cpSkyIsrExp
- cpSkyMaskedIsrExp
- cti_vs_flux
- dark
- darkBin64
- darkBin8
- darkBootstrap
- darkMosaic64
- darkMosaic8
- dark_current_stats
- dark_defects_results
- dcrCoadd
- dcrCoadd_nImage
- deblendCoaddFootprints_resource_usage
- deblend_resource_usage
- decals_dr10
- deconvolved_deep_coadd
- deepCoadd
- deepCoaddPsfMatched
- deepCoadd_Sersic_multiprofit
- deepCoadd_artifactEpochCountImage
- deepCoadd_calexp
- deepCoadd_calexpBin
- deepCoadd_directWarp
- deepCoadd_directWarp_bgMatched
- deepCoadd_directWarp_maskedFraction
- deepCoadd_hpx
- deepCoadd_nImage
- deepCoadd_obj
- deepCoadd_psfMatchedWarp
- deepCoadd_psfs_multiprofit
- deep_coadd
- deep_coadd_compare_template
- deep_coadd_hf_background_image
- deep_coadd_hf_subtracted
- deep_coadd_lf_background_image
- deep_coadd_lf_subtracted
- deep_coadd_lf_subtracted_binned
- deep_coadd_n_image
- deep_coadd_predetection
- deep_coadd_predetection_binned
- deep_hf_background_image
- deep_hf_subtracted_binned
- deep_lf_background_image
- deep_lf_subtracted_binned
- depth
- des_y3gold
- detectAndMeasureDiaSource_resource_usage
- detectAndMeasureDiaSources_resource_usage
- detectCoaddPeaks_resource_usage
- detection_resource_usage
- diaObjectTable_tract
- diaSourceTable
- diaSourceTable_tract
- dia_forced_source_apdb
- dia_object
- dia_object_apdb
- dia_object_forced_source
- dia_object_forced_source_unstandardized
- dia_object_patch
- dia_object_pre_calc
- dia_source
- dia_source_apdb
- dia_source_detector
- dia_source_patch
- dia_source_visit
- difference_image
- difference_image_binned
- difference_image_metrics
- difference_image_predetection
- difference_image_visit_mosaic
- direct_warp
- divisadero_stats
- donutCatalog
- donutsExtraQuality
- donutsIntraQuality
- drpAssociation_resource_usage
- drpDiaCalculation_resource_usage
- eoDarkIsr
- eoDarkProc
- eoFlatIsr
- eoFpMosaic
- eo_dark
- eo_flat
- eo_read_noise
- eo_vampire_defect_catalog
- eper_stats
- expCorrected
- expUncorrected
- fakes_goodSeeingDiff_assocDiaSrc
- fakes_goodSeeingDiff_diaForcedSrc
- fakes_goodSeeingDiff_diaObject
- fakes_goodSeeingDiff_diaSrcTable
- fakes_goodSeeingDiff_differenceExp
- fakes_goodSeeingDiff_differenceTempExp
- fakes_goodSeeingDiff_longTrailedSrc
- fakes_goodSeeingDiff_matchDiaSourceTable
- fakes_goodSeeingDiff_matchDiaSrc
- fakes_goodSeeingDiff_matchedExp
- fakes_goodSeeingDiff_spatiallySampledMetrics
- fakes_goodSeeingDiff_templateExp
- fakes_initial_pvi
- fakes_initial_pvi_catalog
- fgcmBuildFromIsolatedStars_resource_usage
- fgcmFitCycle_resource_usage
- fgcmOutputProducts_resource_usage
- fgcm_reference_stars
- fgcm_star_ids
- fgcm_star_observations
- filterDiaSource_resource_usage
- finalizeCharacterization_resource_usage
- finalized_src_table
- fitDeblendedObjectsSersic_resource_usage
- fitDeepCoaddPsfGaussians_resource_usage
- fitVisitBackground_resource_usage
- flat
- flatBin64
- flatBin8
- flatBlueBin64
- flatBlueBin8
- flatBlueMosaic64
- flatBlueMosaic8
- flatBootstrap
- flatMosaic64
- flatMosaic8
- flatRedBin64
- flatRedBin8
- flatRedMosaic64
- flatRedMosaic8
- flat_blue
- flat_gain_stability_stats
- flat_m730l5
- flat_m730l5_bin64
- flat_m730l5_bin8
- flat_m730l5_mosaic64
- flat_m730l5_mosaic8
- flat_m810l3
- flat_m810l3_bin64
- flat_m810l3_bin8
- flat_m810l3_mosaic64
- flat_m810l3_mosaic8
- flat_m850l3
- flat_m850l3_bin64
- flat_m850l3_bin8
- flat_m850l3_mosaic64
- flat_m850l3_mosaic8
- flat_m940l3
- flat_m940l3_bin64
- flat_m940l3_bin8
- flat_m940l3_mosaic64
- flat_m940l3_mosaic8
- flat_red
- forcedPhotCcdOnDiaObjects_resource_usage
- forcedPhotCcd_resource_usage
- forcedPhotCoadd_resource_usage
- forcedPhotDiaObjectDifference_resource_usage
- forcedPhotDiaObjectDirect_resource_usage
- forcedPhotDiffOnDiaObjects_resource_usage
- forcedPhotDiffim_resource_usage
- forcedPhotObjectDifference_resource_usage
- forcedPhotObjectDirect_resource_usage
- forcedSourceOnDiaObjectTable
- forcedSourceOnDiaObjectTable_tract
- forcedSourceTable
- forcedSourceTable_tract
- fringe
- gbdesAstrometricFit_cameraModel
- gbdesAstrometricFit_dcrCoefficients
- gbdesAstrometricFit_fitStars
- gbdesAstrometricFit_modelParams
- gbdesAstrometricFit_resource_usage
- gbdesAstrometricFit_starCatalog
- gbdesGlobalAstrometricFit_dcrCoefficients
- gbdesGlobalAstrometricFit_fitStars
- gbdesGlobalAstrometricFit_starCatalog
- getTemplate_resource_usage
- goodSeeingCoadd
- goodSeeingCoadd_directWarp
- goodSeeingCoadd_hpx
- goodSeeingCoadd_nImage
- goodSeeingCoadd_psfMatchedWarp
- goodSeeingDiff_assocDiaSrc
- goodSeeingDiff_assocDiaSrcTable
- goodSeeingDiff_associatedSsSources
- goodSeeingDiff_diaForcedSrc
- goodSeeingDiff_diaObjTable
- goodSeeingDiff_diaObject
- goodSeeingDiff_diaSrcTable
- goodSeeingDiff_differenceExp
- goodSeeingDiff_differenceTempExp
- goodSeeingDiff_fullDiaObjTable
- goodSeeingDiff_longTrailedSrc
- goodSeeingDiff_matchedExp
- goodSeeingDiff_scoreExp
- goodSeeingDiff_spatiallySampledMetrics
- goodSeeingDiff_streaks
- goodSeeingDiff_templateExp
- healSparsePropertyMaps_resource_usage
- icExp
- icExpCorrected
- icExpCorrectedNoBkg
- icExpUncorrected
- icExpUncorrectedNoBkg
- illuminationCorrection
- initial_psf_stars_detector
- initial_pvi
- initial_stars_detector
- injected_background_to_photometric_ratio
- injected_calexp
- injected_deepCoadd
- injected_deepCoadd_calexp
- injected_deepCoadd_catalog
- injected_deepCoadd_catalog_tract
- injected_deepCoadd_obj
- injected_goodSeeingDiff_diaSrcTable
- injected_goodSeeingDiff_differenceExp
- injected_goodSeeingDiff_differenceTempExp
- injected_goodSeeingDiff_matchDiaSourceTable
- injected_goodSeeingDiff_matchPVIDiaSrc
- injected_goodSeeingDiff_matchedExp
- injected_goodSeeingDiff_templateExp
- injected_initial_psf_stars_detector
- injected_mergedForcedSource
- injected_objectTable
- injected_objectTable_tract
- injected_objectTable_tract_the_monster_20240904_match_astrom
- injected_objectTable_tract_the_monster_20240904_match_photom
- injected_object_epoch
- injected_postISRCCD
- injected_postISRCCD_catalog
- injected_preSource
- injected_preSourceTable
- injected_pvi
- injected_pvi_catalog
- injected_slsim_calexp_catalog
- injection_catalog
- injection_slsim
- isolatedStarAssociation_resource_usage
- isolatedStarSourceAssociation_resource_usage
- isolated_analysis_source
- isolated_analysis_source_association
- isolated_star
- isolated_star_association
- isolated_star_cat
- isolated_star_presource_associations
- isolated_star_presources
- isolated_star_source_associations
- isolated_star_sources
- isrOverscanCorrected
- isr_resource_usage
- limiting_surface_brightness_hist
- limiting_surface_brightness_table
- linearity_results
- long_trailed_dia_source
- long_trailed_source_detector
- makeAnalysisRecalibratedStarAssociationMetricTable_resource_usage
- makeAnalysisRecalibratedStarAssociationWholeSkyPlot_resource_usage
- makeAnalysisSingleVisitStarAssociationMetricTable_resource_usage
- makeAnalysisSingleVisitStarAssociationWholeSkyPlot_resource_usage
- makeAnalysisSingleVisitStarAstrometricRefMatch_resource_usage
- makeAnalysisSingleVisitStarPhotometricRefMatch_resource_usage
- makeAnalysisSourceAssociationMetricTable_resource_usage
- makeAnalysisSourceAssociationWholeSkyPlot_resource_usage
- makeCcdVisitTable_resource_usage
- makeDirectWarp_resource_usage
- makeHealSparsePropertyMaps_resource_usage
- makeInitialVisitDetectorTable_resource_usage
- makeInitialVisitTable_resource_usage
- makeMetricTableMatchedVisitCore_resource_usage
- makeMetricTableObjectTableCoreRefCatMatch_resource_usage
- makeMetricTableObjectTableCore_resource_usage
- makePreliminaryCcdVisitTable_resource_usage
- makePreliminaryVisitTable_resource_usage
- makePsfMatchedWarp_resource_usage
- makeVisitDetectorTable_resource_usage
- makeVisitTable_resource_usage
- makeWarp_resource_usage
- marginal_new_dia_source
- match_ref_cdfs_hlf_v2p1_objectTable_tract
- match_ref_cosmos2020_classic_v2p2_object
- match_ref_cosmos_acs_iphot_200709_object
- match_ref_decals_dr10_objectTable_tract
- match_ref_des_y3gold_objectTable_tract
- match_ref_injected_deepCoadd_catalog_tract_injected_objectTable_tract
- match_ref_rc2_object_hsc_object
- match_target_cdfs_hlf_v2p1_objectTable_tract
- match_target_cosmos2020_classic_v2p2_object
- match_target_cosmos_acs_iphot_200709_object
- match_target_decals_dr10_objectTable_tract
- match_target_des_y3gold_objectTable_tract
- match_target_injected_deepCoadd_catalog_tract_injected_objectTable_tract
- match_target_rc2_object_hsc_object
- matchedVisitCoreWholeSkyPlot_resource_usage
- matchedVisitCore_metricsTable
- matched_cdfs_hlf_v2p1_objectTable_tract
- matched_cosmos2020_classic_v2p2_object
- matched_cosmos_acs_iphot_200709_object
- matched_decals_dr10_objectTable_tract
- matched_des_y3gold_objectTable_tract
- matched_injected_deepCoadd_catalog_tract_injected_objectTable_tract
- matched_rc2_object_hsc_object
- measureObjectForced_resource_usage
- measureObjectUnforced_resource_usage
- measure_resource_usage
- mergeDetections_resource_usage
- mergeMeasurements_resource_usage
- mergeObjectDetection_resource_usage
- mergeObjectMeasurement_resource_usage
- mergedForcedSource
- mergedForcedSourceOnDiaObject
- nImagePatch_tract
- nImageTable_tract
- new_dia_source
- object
- objectEpochTable_resource_usage
- objectTable
- objectTableCoreRefCatMatchWholeSkyPlot_resource_usage
- objectTableCoreWholeSkyPlot_resource_usage
- objectTableCore_metricsTable
- objectTable_tract
- objectTable_tract_atlas_refcat2_20220201_match
- objectTable_tract_atlas_refcat2_20220201_match_photom
- objectTable_tract_gaia_dr3_20230707_match
- objectTable_tract_gaia_dr3_20230707_match_astrom
- objectTable_tract_gaia_dr3_20230707_match_astrom_metricsTable
- objectTable_tract_multiprofit
- objectTable_tract_the_monster_20240904_match
- objectTable_tract_the_monster_20240904_match_astrom
- objectTable_tract_the_monster_20240904_match_photom
- objectTable_tract_uw_stars_20240524_match
- objectTable_tract_uw_stars_20240524_photoMatch
- object_all
- object_epoch
- object_forced_source
- object_forced_source_all
- object_forced_source_nonprimary
- object_forced_source_unstandardized
- object_metrics_table
- object_nonprimary
- object_patch
- object_psf_multiprofit
- object_ref_match_astrom
- object_ref_match_astrom_metrics_table
- object_ref_match_photom
- object_sersic_multiprofit
- object_unstandardized
- persistence_data
- phosphorescent_defects_results
- photometricCatalogMatch_resource_usage
- photometricRefCatObjectTract_resource_usage
- photometric_to_background_ratio_warp
- plotPropertyMapSurvey_resource_usage
- plotPropertyMapTract_resource_usage
- postFitPostISRCCD
- postISRCCD
- postIsrBin1
- postIsrBin2
- post_isr_image
- preCcdVisitTable
- preSource
- preSourceTable
- preSourceTable_visit
- preSourceTable_visit_gaia_dr3_20230707_match_astrom
- preSourceTable_visit_the_monster_20240904_match_astrom
- preSourceTable_visit_uw_stars_20240524_match
- preSourceTable_visit_uw_stars_20240524_match_astrom
- preVisitTable
- preliminary_visit_detector_table
- preliminary_visit_image
- preliminary_visit_image_background_mask_extended
- preliminary_visit_image_background_skyCorr_visit_mosaic
- preliminary_visit_image_background_skyCorr_visit_mosaic_experimental
- preliminary_visit_image_mask_extended
- preliminary_visit_image_skyCorr_visit_mosaic
- preliminary_visit_image_skyCorr_visit_mosaic_experimental
- preliminary_visit_table
- preloaded_DRP_SsObjects
- preloaded_SsObjects
- preloaded_diaForcedSources
- preloaded_diaObjects
- preloaded_diaSources
- preloaded_dia_forced_source
- preloaded_dia_object
- preloaded_dia_source
- preloaded_ss_object
- pretty_picture_coadd_bg_subtracted
- pretty_picture_coadd_fixed_stars
- psf_matched_warp
- ptc_summary
- pvi
- raw
- rbClassify_resource_usage
- rc2_object_hsc
- recalibrateSingleVisitStar_resource_usage
- recalibrated_star
- recalibrated_star_association_metrics_table
- recalibrated_star_detector
- recalibrated_star_ref_match_astrom
- recalibrated_star_unstandardized
- refCatObjectTract_resource_usage
- refitPsfModelDetector_resource_usage
- refit_psf_star
- refit_psf_star_detector
- reprocessVisitImage_resource_usage
- rewarpTemplate_resource_usage
- rewriteObject_resource_usage
- rgb_picture_mask
- row_means_variance_stats
- selectDeepCoaddVisits_resource_usage
- selectGoodSeeingVisits_resource_usage
- selectTemplateCoaddVisits_resource_usage
- single_visit_psf_star
- single_visit_star
- single_visit_star_association_metrics_table
- single_visit_star_detector
- single_visit_star_ref_match_astrom
- single_visit_star_ref_match_photom
- single_visit_star_reprocessed_unstandardized
- single_visit_star_unstandardized
- sky
- skyCorrExperimental_resource_usage
- skyCorr_resource_usage
- source
- source2
- sourceObjectMatch_resource_usage
- sourceTable
- sourceTable_visit
- source_all
- source_detector
- source_nonprimary
- source_ref_match_photom
- source_unstandardized
- sources_detector
- splitPrimaryObjectForcedSource_resource_usage
- splitPrimaryObject_resource_usage
- splitPrimarySource_resource_usage
- ssAssociatedSingleFrameSources
- ssSingleFrameAssociatedSources
- ssSingleFrameUnassociatedObjects
- ssUnassociatedObjects
- ss_object
- ss_object_direct_unassociated
- ss_object_unassociated
- ss_object_unassociated_detector
- ss_source
- ss_source_associated
- ss_source_detector
- ss_source_direct_detector
- standardizeDiaObjectForcedSource_resource_usage
- standardizeDiaSource_resource_usage
- standardizeObjectForcedSource_resource_usage
- standardizeObject_resource_usage
- standardizeRecalibratedStar_resource_usage
- standardizeSingleVisitStar_resource_usage
- standardizeSource_resource_usage
- subtractImages_resource_usage
- templateCoadd_hpx
- templateGen_resource_usage
- templateTableCore_tract
- template_coadd
- template_coadd_binned
- template_coadd_hf_subtracted
- template_coadd_lf_subtracted
- template_coadd_lf_subtracted_binned
- template_coadd_n_image
- template_des_detector
- template_detector
- template_hf_background_image
- template_lf_background_image
- template_lf_subtracted_binned
- template_matched
- trailed_glint_parameters
- trailed_glints
- transformDiaSourceCat_resource_usage
- transformForcedSourceOnDiaObjectTable_resource_usage
- transformForcedSourceTable_resource_usage
- transformObjectTable_resource_usage
- transformPreSourceTable_resource_usage
- transformSourceTable_resource_usage
- updateVisitSummary_resource_usage
- validateObjectTableCore_resource_usage
- verifyBiasDetMatrix
- verifyBiasDetResults
- verifyBiasExpMatrix
- verifyBiasExpResults
- verifyBiasIsrExp
- verifyBiasIsrExpBin64
- verifyBiasIsrExpBin8
- verifyBiasMatrix
- verifyBiasResidual64
- verifyBiasResidual8
- verifyBiasResults
- verifyDarkDetResults
- verifyDarkExpResults
- verifyDarkIsrExp
- verifyDarkIsrExpBin64
- verifyDarkIsrExpBin8
- verifyDarkResidual64
- verifyDarkResidual8
- verifyDarkResults
- verifyDefectsDetResults
- verifyDefectsExpResults
- verifyDefectsIcExp
- verifyDefectsIsrExp
- verifyDefectsResults
- verifyFlatDetMergeResults
- verifyFlatDetResults
- verifyFlatExpResults
- verifyFlatIsrExp
- verifyFlatIsrExpBin64
- verifyFlatIsrExpBin8
- verifyFlatResidual64
- verifyFlatResidual8
- verifyFlatResults
- verifyScience64
- verifyScience8
- verifyScienceIsrExp
- verifyScienceIsrExpBin64
- verifyScienceIsrExpBin8
- verifyUncorrectedDefectsIcExp
- verifyUncorrectedDefectsIsrExp
- visitTable
- visit_detector_table
- visit_image
- visit_table
- writeDiaObjectForcedSource_resource_usage
- writeForcedSourceOnDiaObjectTable_resource_usage
- writeForcedSourceTable_resource_usage
- writeObjectForcedSource_resource_usage
- writeObjectTable_resource_usage
- writePreSourceTable_resource_usage
- writeRecalibratedSourceTable_resource_usage
